package serb.tp.metro.blocks;

import cpw.mods.fml.common.registry.GameRegistry;
import net.minecraft.block.Block;
import net.minecraft.block.material.Material;
import serb.tp.metro.blocks.tiles.TileEntityRediction;
import serb.tp.metro.creativetabs.LoadTabs;

public class LoadBlocks
{
	
    public static final Block
    	marble_gray_1 = new BuildersBlock(Material.rock, "marble_gray_1", 0),
    	marble_gray_2 = new BuildersBlock(Material.rock, "marble_gray_2", 0),
    	marble_gray_3 = new BuildersBlock(Material.rock, "marble_gray_3", 0),
    	marble_gray_4 = new BuildersBlock(Material.rock, "marble_gray_4", 0),
    	marble_gray_5 = new BuildersBlock(Material.rock, "marble_gray_5", 0),
    	marble_white_1 = new BuildersBlock(Material.rock, "marble_white_1", 0),
    	marble_white_2 = new BuildersBlock(Material.rock, "marble_white_2", 0),
    	marble_white_3 = new BuildersBlock(Material.rock, "marble_white_3", 0),
    	marble_white_4 = new BuildersBlock(Material.rock, "marble_white_4", 0),
    	marble_black_1 = new BuildersBlock(Material.rock, "marble_black_1", 0),
    	marble_black_2 = new BuildersBlock(Material.rock, "marble_black_2", 0),
    	marble_black_3 = new BuildersBlock(Material.rock, "marble_black_3", 0),
    	marble_yellow_1 = new BuildersBlock(Material.rock, "marble_yellow_1", 0),
    	marble_yellow_2 = new BuildersBlock(Material.rock, "marble_yellow_2", 0),
    	marble_yellow_3 = new BuildersBlock(Material.rock, "marble_yellow_3", 0),
    	marble_yellow_4 = new BuildersBlock(Material.rock, "marble_yellow_4", 0),
    	marble_yellow_5 = new BuildersBlock(Material.rock, "marble_yellow_5", 0),
    	marble_red_1 = new BuildersBlock(Material.rock, "marble_red_1", 0),
    	marble_red_2 = new BuildersBlock(Material.rock, "marble_red_2", 0),
    	marble_orange_1 = new BuildersBlock(Material.rock, "marble_orange_1", 0),
    	marble_beige_1 = new BuildersBlock(Material.rock, "marble_beige_1", 0),
    	marble_beige_2 = new BuildersBlock(Material.rock, "marble_beige_2", 0),
    	concrete_white_1 = new BuildersBlock(Material.rock, "concrete_white_1", 0),
    	concrete_white_2 = new BuildersBlock(Material.rock, "concrete_white_2", 0),
    	concrete_white_3 = new BuildersBlock(Material.rock, "concrete_white_3", 0),
    	concrete_white_4 = new BuildersBlock(Material.rock, "concrete_white_4", 0),
    	concrete_gray_1 = new BuildersBlock(Material.rock, "concrete_gray_1", 0),
    	concrete_gray_2 = new BuildersBlock(Material.rock, "concrete_gray_2", 0),
    	concrete_gray_3 = new BuildersBlock(Material.rock, "concrete_gray_3", 0),
    	concrete_gray_4 = new BuildersBlock(Material.rock, "concrete_gray_4", 0),
    	concrete_gray_5 = new BuildersBlock(Material.rock, "concrete_gray_5", 0),
    	concrete_gray_6 = new BuildersBlock(Material.rock, "concrete_gray_6", 0),
    	concrete_gray_7 = new BuildersBlock(Material.rock, "concrete_gray_7", 0),
    	concrete_green_1 = new BuildersBlock(Material.rock, "concrete_green_1", 0),
    	concrete_black_1 = new BuildersBlock(Material.rock, "concrete_black_1", 0),
    	concrete_black_2 = new BuildersBlock(Material.rock, "concrete_black_2", 0),
    	mosaic_gray_1 = new BuildersBlock(Material.rock, "mosaic_gray_1", 0),
    	mosaic_white_1 = new BuildersBlock(Material.rock, "mosaic_white_1", 0),
    	mosaic_white_2 = new BuildersBlock(Material.rock, "mosaic_white_2", 0),
    	old_concrete_gray_1 = new BuildersBlock(Material.rock, "old_concrete_gray_1", 0),
    	old_concrete_gray_2 = new BuildersBlock(Material.rock, "old_concrete_gray_2", 0),
    	tiles_beige_1 = new BuildersBlock(Material.rock, "tiles_beige_1", 0),
    	tiles_beige_2 = new BuildersBlock(Material.rock, "tiles_beige_2", 0),
    	tiles_black_1 = new BuildersBlock(Material.rock, "tiles_black_1", 0),
    	tiles_black_2 = new BuildersBlock(Material.rock, "tiles_black_2", 0),
    	tiles_gray_1 = new BuildersBlock(Material.rock, "tiles_gray_1", 0),
    	tiles_gray_2 = new BuildersBlock(Material.rock, "tiles_gray_2", 0),
    	tiles_gray_3 = new BuildersBlock(Material.rock, "tiles_gray_3", 0),
    	tiles_gray_4 = new BuildersBlock(Material.rock, "tiles_gray_4", 0),
    	tiles_gray_5 = new BuildersBlock(Material.rock, "tiles_gray_5", 0),
    	tiles_gray_6 = new BuildersBlock(Material.rock, "tiles_gray_6", 0),
		tiles_white_1 = new BuildersBlock(Material.rock, "tiles_white_1", 0),
		tiles_white_2 = new BuildersBlock(Material.rock, "tiles_white_2", 0),
		tiles_white_3 = new BuildersBlock(Material.rock, "tiles_white_3", 0),
    	tiles_red_1 = new BuildersBlock(Material.rock, "tiles_red_1", 0),
    	tiles_red_2 = new BuildersBlock(Material.rock, "tiles_red_2", 0),
    	tiles_red_3 = new BuildersBlock(Material.rock, "tiles_red_3", 0),
    	tiles_red_4 = new BuildersBlock(Material.rock, "tiles_red_4", 0),
    	tiles_yellow_1 = new BuildersBlock(Material.rock, "tiles_yellow_1", 0),
    	concrete_brick_1 = new BuildersBlock(Material.rock, "concrete_brick_1", 0),
    	bronze_1 = new BuildersBlock(Material.iron, "bronze_1", 0),
    	bricks_old_1 = new BuildersBlock(Material.rock, "bricks_old_1", 0),
    	bricks_red_1 = new BuildersBlock(Material.rock, "bricks_red_1", 0),
    	bricks_red_2 = new BuildersBlock(Material.rock, "bricks_red_2", 0),
    	bricks_red_3 = new BuildersBlock(Material.rock, "bricks_red_3", 0),
    	bricks_red_4 = new BuildersBlock(Material.rock, "bricks_red_4", 0),
    	bricks_red_5 = new BuildersBlock(Material.rock, "bricks_red_5", 0),
    	bricks_stone_1 = new BuildersBlock(Material.rock, "bricks_stone_1", 0),
    	bricks_yellow_1 = new BuildersBlock(Material.rock, "bricks_yellow_1", 0),
    	bricks_yellow_2 = new BuildersBlock(Material.rock, "bricks_yellow_2", 0),
    	granite_black_1 = new BuildersBlock(Material.rock, "granite_black_1", 0),
    	granite_black_2 = new BuildersBlock(Material.rock, "granite_black_2", 0),
    	granite_black_3 = new BuildersBlock(Material.rock, "granite_black_3", 0),
    	granite_black_4 = new BuildersBlock(Material.rock, "granite_black_4", 0),
    	granite_brown_1 = new BuildersBlock(Material.rock, "granite_brown_1", 0),
    	granite_brown_2 = new BuildersBlock(Material.rock, "granite_brown_2", 0),
    	granite_brown_3 = new BuildersBlock(Material.rock, "granite_brown_3", 0),
    	granite_beige_1 = new BuildersBlock(Material.rock, "granite_beige_1", 0),
    	granite_beige_2 = new BuildersBlock(Material.rock, "granite_beige_2", 0),
    	granite_beige_3 = new BuildersBlock(Material.rock, "granite_beige_3", 0),
    	granite_beige_4 = new BuildersBlock(Material.rock, "granite_beige_4", 0),
    	granite_white_1 = new BuildersBlock(Material.rock, "granite_white_1", 0),
    	granite_gray_1 = new BuildersBlock(Material.rock, "granite_gray_1", 0),
    	granite_gray_2 = new BuildersBlock(Material.rock, "granite_gray_2", 0),
    	blockInvisible = new BlockInvisible("blockInvisible"),
    	blockRediction = new BlockRediction("BlockRediction"),
    	blockLamp = new BuildersBlock(Material.glass, "lamp_1", 3.0F).setStepSound(Block.soundTypeGlass),
    	blockRedictionUnbreakable = new BlockRediction("blockRedictionUnbreakable").setBlockUnbreakable().setHardness(600000F),
    	tiles_green_1 = new BuildersBlock(Material.rock, "tiles_green_1", 0),
    	marble_green_1 = new BuildersBlock(Material.rock, "marble_green_1", 0)
    	;	
    	
}
